"""Not initial migration

Revision ID: 2f7d61ee22d7
Revises: 
Create Date: 2023-03-28 09:27:00.882764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f7d61ee22d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.String(length=100), nullable=True))
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
